### ISSUE TITLE
Rename conda package of numba-extensions-bf16 to `numba_extensions.bf16`

### ISSUE THREAD

**Issue by isVoid** [NVIDIA/numbast#48]

**Comment by gmarkall** [comment]
A couple of thoughts:

* Is there a more uncommon name we could use for this? I'm thinking a lot of people might write a `numba_extensions` module in their project.
* Was the top level package going to be a namespace package? I've no experience with them, but I have avoided using them in the past because I was concerned it would be easy to cause confusing issues with them if someone makes an error in one of the sub-packages (this may be an unfounded concern, I just don't know).

**Comment by quasiben** [comment]
re-opening to continue discussing @gmarkall's thoughts
